# Generated by Django 3.2.4 on 2021-06-18 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alkalinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.IntegerField()),
                ('message', models.CharField(max_length=175)),
            ],
        ),
        migrations.CreateModel(
            name='CyanuricAcid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.IntegerField()),
                ('message', models.CharField(max_length=175)),
            ],
        ),
        migrations.CreateModel(
            name='FilterPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psi', models.IntegerField()),
                ('message', models.CharField(max_length=175)),
            ],
        ),
        migrations.CreateModel(
            name='FreeChlorine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.IntegerField()),
                ('message', models.CharField(max_length=175)),
            ],
        ),
        migrations.CreateModel(
            name='Hardness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.IntegerField()),
                ('message', models.CharField(max_length=175)),
            ],
        ),
        migrations.CreateModel(
            name='Ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('message', models.CharField(max_length=175)),
            ],
        ),
        migrations.CreateModel(
            name='PumpHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.IntegerField()),
                ('message', models.CharField(max_length=175)),
            ],
        ),
        migrations.CreateModel(
            name='TotalChlorine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppm', models.IntegerField()),
                ('message', models.CharField(max_length=175)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PumphouseParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hardness_note', models.CharField(max_length=175)),
                ('chlorine_note', models.CharField(max_length=175)),
                ('ph_note', models.CharField(max_length=175)),
                ('alkalinity_note', models.CharField(max_length=175)),
                ('cyanuric_acid_note', models.CharField(max_length=175)),
                ('salinity_note', models.CharField(max_length=175)),
                ('filter_pressure_note', models.CharField(max_length=175)),
                ('filter_basket', models.BooleanField()),
                ('alkalinity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueflamingoapi.alkalinity')),
                ('cyanuric_acid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueflamingoapi.cyanuricacid')),
                ('filter_pressure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueflamingoapi.filterpressure')),
                ('free_chlorine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueflamingoapi.freechlorine')),
                ('hardness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueflamingoapi.hardness')),
                ('ph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueflamingoapi.ph')),
                ('pumphouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blueflamingoapi.pumphouse')),
                ('salinity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueflamingoapi.salinity')),
                ('total_chlorine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueflamingoapi.totalchlorine')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
