# Generated by Django 3.2.4 on 2021-06-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueflamingoapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pumphouseparameters',
            old_name='Pumphouse',
            new_name='pumphouse',
        ),
        migrations.AlterField(
            model_name='pumphouse',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
