# Generated by Django 3.2.4 on 2021-06-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueflamingoapi', '0002_auto_20210610_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pumphouseparameters',
            old_name='hardness_notes',
            new_name='hardness_note',
        ),
    ]
